# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabylonDemo-MVC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabylonDemo-MVC

  target 'BabylonDemo-MVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BabylonDemo-MVCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
